/*
 * This file is generated by jOOQ.
 */
package com.getartur.billingcore.shared.domain.jooq.tables.records;


import com.getartur.billingcore.shared.domain.jooq.tables.Invoice;

import java.time.LocalDate;
import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InvoiceRecord extends UpdatableRecordImpl<InvoiceRecord> implements Record8<Long, Long, String, LocalDate, String, String, String, LocalDateTime> {

    private static final long serialVersionUID = -163432760;

    /**
     * Setter for <code>getartur.invoice.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>getartur.invoice.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>getartur.invoice.customer_id</code>.
     */
    public void setCustomerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>getartur.invoice.customer_id</code>.
     */
    public Long getCustomerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>getartur.invoice.number</code>.
     */
    public void setNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>getartur.invoice.number</code>.
     */
    public String getNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>getartur.invoice.issued</code>.
     */
    public void setIssued(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>getartur.invoice.issued</code>.
     */
    public LocalDate getIssued() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>getartur.invoice.delivery</code>.
     */
    public void setDelivery(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>getartur.invoice.delivery</code>.
     */
    public String getDelivery() {
        return (String) get(4);
    }

    /**
     * Setter for <code>getartur.invoice.intro</code>.
     */
    public void setIntro(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>getartur.invoice.intro</code>.
     */
    public String getIntro() {
        return (String) get(5);
    }

    /**
     * Setter for <code>getartur.invoice.outro</code>.
     */
    public void setOutro(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>getartur.invoice.outro</code>.
     */
    public String getOutro() {
        return (String) get(6);
    }

    /**
     * Setter for <code>getartur.invoice.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>getartur.invoice.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, String, LocalDate, String, String, String, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, String, LocalDate, String, String, String, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Invoice.INVOICE.ID;
    }

    @Override
    public Field<Long> field2() {
        return Invoice.INVOICE.CUSTOMER_ID;
    }

    @Override
    public Field<String> field3() {
        return Invoice.INVOICE.NUMBER;
    }

    @Override
    public Field<LocalDate> field4() {
        return Invoice.INVOICE.ISSUED;
    }

    @Override
    public Field<String> field5() {
        return Invoice.INVOICE.DELIVERY;
    }

    @Override
    public Field<String> field6() {
        return Invoice.INVOICE.INTRO;
    }

    @Override
    public Field<String> field7() {
        return Invoice.INVOICE.OUTRO;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return Invoice.INVOICE.CREATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCustomerId();
    }

    @Override
    public String component3() {
        return getNumber();
    }

    @Override
    public LocalDate component4() {
        return getIssued();
    }

    @Override
    public String component5() {
        return getDelivery();
    }

    @Override
    public String component6() {
        return getIntro();
    }

    @Override
    public String component7() {
        return getOutro();
    }

    @Override
    public LocalDateTime component8() {
        return getCreated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCustomerId();
    }

    @Override
    public String value3() {
        return getNumber();
    }

    @Override
    public LocalDate value4() {
        return getIssued();
    }

    @Override
    public String value5() {
        return getDelivery();
    }

    @Override
    public String value6() {
        return getIntro();
    }

    @Override
    public String value7() {
        return getOutro();
    }

    @Override
    public LocalDateTime value8() {
        return getCreated();
    }

    @Override
    public InvoiceRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public InvoiceRecord value2(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public InvoiceRecord value3(String value) {
        setNumber(value);
        return this;
    }

    @Override
    public InvoiceRecord value4(LocalDate value) {
        setIssued(value);
        return this;
    }

    @Override
    public InvoiceRecord value5(String value) {
        setDelivery(value);
        return this;
    }

    @Override
    public InvoiceRecord value6(String value) {
        setIntro(value);
        return this;
    }

    @Override
    public InvoiceRecord value7(String value) {
        setOutro(value);
        return this;
    }

    @Override
    public InvoiceRecord value8(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public InvoiceRecord values(Long value1, Long value2, String value3, LocalDate value4, String value5, String value6, String value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InvoiceRecord
     */
    public InvoiceRecord() {
        super(Invoice.INVOICE);
    }

    /**
     * Create a detached, initialised InvoiceRecord
     */
    public InvoiceRecord(Long id, Long customerId, String number, LocalDate issued, String delivery, String intro, String outro, LocalDateTime created) {
        super(Invoice.INVOICE);

        set(0, id);
        set(1, customerId);
        set(2, number);
        set(3, issued);
        set(4, delivery);
        set(5, intro);
        set(6, outro);
        set(7, created);
    }
}
