/*
 * This file is generated by jOOQ.
 */
package com.getartur.billingcore.shared.domain.jooq.tables.records;


import com.getartur.billingcore.shared.domain.jooq.tables.Project;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> implements Record7<Long, Long, String, LocalDate, LocalDate, BigDecimal, String> {

    private static final long serialVersionUID = 501934503;

    /**
     * Setter for <code>getartur.project.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>getartur.project.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>getartur.project.customer_id</code>.
     */
    public void setCustomerId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>getartur.project.customer_id</code>.
     */
    public Long getCustomerId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>getartur.project.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>getartur.project.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>getartur.project.started</code>.
     */
    public void setStarted(LocalDate value) {
        set(3, value);
    }

    /**
     * Getter for <code>getartur.project.started</code>.
     */
    public LocalDate getStarted() {
        return (LocalDate) get(3);
    }

    /**
     * Setter for <code>getartur.project.finished</code>.
     */
    public void setFinished(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>getartur.project.finished</code>.
     */
    public LocalDate getFinished() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>getartur.project.rate</code>.
     */
    public void setRate(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>getartur.project.rate</code>.
     */
    public BigDecimal getRate() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>getartur.project.rate_type</code>.
     */
    public void setRateType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>getartur.project.rate_type</code>.
     */
    public String getRateType() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, String, LocalDate, LocalDate, BigDecimal, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, String, LocalDate, LocalDate, BigDecimal, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Project.PROJECT.ID;
    }

    @Override
    public Field<Long> field2() {
        return Project.PROJECT.CUSTOMER_ID;
    }

    @Override
    public Field<String> field3() {
        return Project.PROJECT.NAME;
    }

    @Override
    public Field<LocalDate> field4() {
        return Project.PROJECT.STARTED;
    }

    @Override
    public Field<LocalDate> field5() {
        return Project.PROJECT.FINISHED;
    }

    @Override
    public Field<BigDecimal> field6() {
        return Project.PROJECT.RATE;
    }

    @Override
    public Field<String> field7() {
        return Project.PROJECT.RATE_TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCustomerId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public LocalDate component4() {
        return getStarted();
    }

    @Override
    public LocalDate component5() {
        return getFinished();
    }

    @Override
    public BigDecimal component6() {
        return getRate();
    }

    @Override
    public String component7() {
        return getRateType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCustomerId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public LocalDate value4() {
        return getStarted();
    }

    @Override
    public LocalDate value5() {
        return getFinished();
    }

    @Override
    public BigDecimal value6() {
        return getRate();
    }

    @Override
    public String value7() {
        return getRateType();
    }

    @Override
    public ProjectRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public ProjectRecord value2(Long value) {
        setCustomerId(value);
        return this;
    }

    @Override
    public ProjectRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public ProjectRecord value4(LocalDate value) {
        setStarted(value);
        return this;
    }

    @Override
    public ProjectRecord value5(LocalDate value) {
        setFinished(value);
        return this;
    }

    @Override
    public ProjectRecord value6(BigDecimal value) {
        setRate(value);
        return this;
    }

    @Override
    public ProjectRecord value7(String value) {
        setRateType(value);
        return this;
    }

    @Override
    public ProjectRecord values(Long value1, Long value2, String value3, LocalDate value4, LocalDate value5, BigDecimal value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(Long id, Long customerId, String name, LocalDate started, LocalDate finished, BigDecimal rate, String rateType) {
        super(Project.PROJECT);

        set(0, id);
        set(1, customerId);
        set(2, name);
        set(3, started);
        set(4, finished);
        set(5, rate);
        set(6, rateType);
    }
}
