/*
 * This file is generated by jOOQ.
 */
package com.getartur.billingcore.shared.domain.jooq.tables.records;


import com.getartur.billingcore.shared.domain.jooq.tables.TimeTracking;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeTrackingRecord extends UpdatableRecordImpl<TimeTrackingRecord> implements Record9<Long, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, LocalDateTime> {

    private static final long serialVersionUID = -399412805;

    /**
     * Setter for <code>getartur.time_tracking.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>getartur.time_tracking.project_id</code>.
     */
    public void setProjectId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.project_id</code>.
     */
    public Long getProjectId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>getartur.time_tracking.invoice_id</code>.
     */
    public void setInvoiceId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.invoice_id</code>.
     */
    public Long getInvoiceId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>getartur.time_tracking.sub_project_id</code>.
     */
    public void setSubProjectId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.sub_project_id</code>.
     */
    public Long getSubProjectId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>getartur.time_tracking.description</code>.
     */
    public void setDescription(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.description</code>.
     */
    public String getDescription() {
        return (String) get(4);
    }

    /**
     * Setter for <code>getartur.time_tracking.start</code>.
     */
    public void setStart(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.start</code>.
     */
    public LocalDateTime getStart() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>getartur.time_tracking.end</code>.
     */
    public void setEnd(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.end</code>.
     */
    public LocalDateTime getEnd() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>getartur.time_tracking.duration_in_minutes</code>.
     */
    public void setDurationInMinutes(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.duration_in_minutes</code>.
     */
    public Integer getDurationInMinutes() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>getartur.time_tracking.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>getartur.time_tracking.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, LocalDateTime> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Long, Long, Long, String, LocalDateTime, LocalDateTime, Integer, LocalDateTime> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TimeTracking.TIME_TRACKING.ID;
    }

    @Override
    public Field<Long> field2() {
        return TimeTracking.TIME_TRACKING.PROJECT_ID;
    }

    @Override
    public Field<Long> field3() {
        return TimeTracking.TIME_TRACKING.INVOICE_ID;
    }

    @Override
    public Field<Long> field4() {
        return TimeTracking.TIME_TRACKING.SUB_PROJECT_ID;
    }

    @Override
    public Field<String> field5() {
        return TimeTracking.TIME_TRACKING.DESCRIPTION;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TimeTracking.TIME_TRACKING.START;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TimeTracking.TIME_TRACKING.END;
    }

    @Override
    public Field<Integer> field8() {
        return TimeTracking.TIME_TRACKING.DURATION_IN_MINUTES;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return TimeTracking.TIME_TRACKING.CREATED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getProjectId();
    }

    @Override
    public Long component3() {
        return getInvoiceId();
    }

    @Override
    public Long component4() {
        return getSubProjectId();
    }

    @Override
    public String component5() {
        return getDescription();
    }

    @Override
    public LocalDateTime component6() {
        return getStart();
    }

    @Override
    public LocalDateTime component7() {
        return getEnd();
    }

    @Override
    public Integer component8() {
        return getDurationInMinutes();
    }

    @Override
    public LocalDateTime component9() {
        return getCreated();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getProjectId();
    }

    @Override
    public Long value3() {
        return getInvoiceId();
    }

    @Override
    public Long value4() {
        return getSubProjectId();
    }

    @Override
    public String value5() {
        return getDescription();
    }

    @Override
    public LocalDateTime value6() {
        return getStart();
    }

    @Override
    public LocalDateTime value7() {
        return getEnd();
    }

    @Override
    public Integer value8() {
        return getDurationInMinutes();
    }

    @Override
    public LocalDateTime value9() {
        return getCreated();
    }

    @Override
    public TimeTrackingRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public TimeTrackingRecord value2(Long value) {
        setProjectId(value);
        return this;
    }

    @Override
    public TimeTrackingRecord value3(Long value) {
        setInvoiceId(value);
        return this;
    }

    @Override
    public TimeTrackingRecord value4(Long value) {
        setSubProjectId(value);
        return this;
    }

    @Override
    public TimeTrackingRecord value5(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public TimeTrackingRecord value6(LocalDateTime value) {
        setStart(value);
        return this;
    }

    @Override
    public TimeTrackingRecord value7(LocalDateTime value) {
        setEnd(value);
        return this;
    }

    @Override
    public TimeTrackingRecord value8(Integer value) {
        setDurationInMinutes(value);
        return this;
    }

    @Override
    public TimeTrackingRecord value9(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public TimeTrackingRecord values(Long value1, Long value2, Long value3, Long value4, String value5, LocalDateTime value6, LocalDateTime value7, Integer value8, LocalDateTime value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TimeTrackingRecord
     */
    public TimeTrackingRecord() {
        super(TimeTracking.TIME_TRACKING);
    }

    /**
     * Create a detached, initialised TimeTrackingRecord
     */
    public TimeTrackingRecord(Long id, Long projectId, Long invoiceId, Long subProjectId, String description, LocalDateTime start, LocalDateTime end, Integer durationInMinutes, LocalDateTime created) {
        super(TimeTracking.TIME_TRACKING);

        set(0, id);
        set(1, projectId);
        set(2, invoiceId);
        set(3, subProjectId);
        set(4, description);
        set(5, start);
        set(6, end);
        set(7, durationInMinutes);
        set(8, created);
    }
}
