spring:
  jpa:
    open-in-view: false
  flyway:
    schemas: ['getartur']
    locations: ['classpath:db/migration/common', 'classpath:db/migration/dev']
  datasource:
    url: ${DB_SERVER_URI:jdbc:mariadb://localhost:4407}/getartur?useUnicode=true&characterEncoding=UTF-8
    username: ${DB_SERVER_USER}
    password: ${DB_SERVER_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      leak-detection-threshold: 31000
      connection-test-query: "SELECT 1"
      minimum-idle: 5
      maximum-pool-size: 5
      auto-commit: false
      pool-name: getartur-pool
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 1800000