/*
 * This file is generated by jOOQ.
 */
package com.getartur.billingcore.shared.domain.jooq;


import com.getartur.billingcore.shared.domain.jooq.tables.Address;
import com.getartur.billingcore.shared.domain.jooq.tables.Customer;
import com.getartur.billingcore.shared.domain.jooq.tables.FlywaySchemaHistory;
import com.getartur.billingcore.shared.domain.jooq.tables.Project;
import com.getartur.billingcore.shared.domain.jooq.tables.TimeTracking;


/**
 * Convenience access to all tables in getartur
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>getartur.address</code>.
     */
    public static final Address ADDRESS = Address.ADDRESS;

    /**
     * The table <code>getartur.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>getartur.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>getartur.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>getartur.time_tracking</code>.
     */
    public static final TimeTracking TIME_TRACKING = TimeTracking.TIME_TRACKING;
}
